name: Ruby CI
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        ruby-version: [3.2, 3.3]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Test
        run: ruby rb/money_test.rb
        shell: bash
